/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * ChangeTransportRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ChangeTransportRequest {
    /**
     * Gets or Sets transporterCode
     */
    @JsonAdapter(TransporterCodeEnum.Adapter.class)
    public enum TransporterCodeEnum {
        BRIEFPOST("BRIEFPOST"),

        UPS("UPS"),

        TNT("TNT"),

        TNT_EXTRA("TNT-EXTRA"),

        TNT_BRIEF("TNT_BRIEF"),

        TNT_EXPRESS("TNT-EXPRESS"),

        DYL("DYL"),

        DPD_NL("DPD-NL"),

        DPD_BE("DPD-BE"),

        BPOST_BE("BPOST_BE"),

        BPOST_BRIEF("BPOST_BRIEF"),

        DHLFORYOU("DHLFORYOU"),

        GLS("GLS"),

        FEDEX_NL("FEDEX_NL"),

        FEDEX_BE("FEDEX_BE"),

        OTHER("OTHER"),

        DHL("DHL"),

        DHL_DE("DHL_DE"),

        DHL_GLOBAL_MAIL("DHL-GLOBAL-MAIL"),

        TSN("TSN"),

        FIEGE("FIEGE"),

        TRANSMISSION("TRANSMISSION"),

        PARCEL_NL("PARCEL-NL"),

        LOGOIX("LOGOIX"),

        PACKS("PACKS"),

        COURIER("COURIER"),

        RJP("RJP");

        private String value;

        TransporterCodeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static TransporterCodeEnum fromValue(String text) {
            for (TransporterCodeEnum b : TransporterCodeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<TransporterCodeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final TransporterCodeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public TransporterCodeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return TransporterCodeEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("transporterCode")
    private TransporterCodeEnum transporterCode = null;

    @SerializedName("trackAndTrace")
    private String trackAndTrace = null;

    public ChangeTransportRequest transporterCode(TransporterCodeEnum transporterCode) {
        this.transporterCode = transporterCode;
        return this;
    }

    /**
     * Get transporterCode
     *
     * @return transporterCode
     **/
    @ApiModelProperty(example = "TNT", value = "")
    public TransporterCodeEnum getTransporterCode() {
        return transporterCode;
    }

    public void setTransporterCode(TransporterCodeEnum transporterCode) {
        this.transporterCode = transporterCode;
    }

    public ChangeTransportRequest trackAndTrace(String trackAndTrace) {
        this.trackAndTrace = trackAndTrace;
        return this;
    }

    /**
     * The track and trace code that is associated with this transport.
     *
     * @return trackAndTrace
     **/
    @ApiModelProperty(example = "3SBOL0987654321", value = "The track and trace code that is associated with this transport.")
    public String getTrackAndTrace() {
        return trackAndTrace;
    }

    public void setTrackAndTrace(String trackAndTrace) {
        this.trackAndTrace = trackAndTrace;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ChangeTransportRequest changeTransportRequest = (ChangeTransportRequest) o;
        return Objects.equals(this.transporterCode, changeTransportRequest.transporterCode) &&
                Objects.equals(this.trackAndTrace, changeTransportRequest.trackAndTrace);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transporterCode, trackAndTrace);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ChangeTransportRequest {\n");

        sb.append("    transporterCode: ").append(toIndentedString(transporterCode)).append("\n");
        sb.append("    trackAndTrace: ").append(toIndentedString(trackAndTrace)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

