/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * CreateUnpublishedOfferReportRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class CreateUnpublishedOfferReportRequest {
    /**
     * The file format in which to return the export.
     */
    @JsonAdapter(FormatEnum.Adapter.class)
    public enum FormatEnum {
        CSV("CSV");

        private String value;

        FormatEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static FormatEnum fromValue(String text) {
            for (FormatEnum b : FormatEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<FormatEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final FormatEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public FormatEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return FormatEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("format")
    private FormatEnum format = null;

    public CreateUnpublishedOfferReportRequest format(FormatEnum format) {
        this.format = format;
        return this;
    }

    /**
     * The file format in which to return the export.
     *
     * @return format
     **/
    @ApiModelProperty(example = "CSV", required = true, value = "The file format in which to return the export.")
    public FormatEnum getFormat() {
        return format;
    }

    public void setFormat(FormatEnum format) {
        this.format = format;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateUnpublishedOfferReportRequest createUnpublishedOfferReportRequest = (CreateUnpublishedOfferReportRequest) o;
        return Objects.equals(this.format, createUnpublishedOfferReportRequest.format);
    }

    @Override
    public int hashCode() {
        return Objects.hash(format);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateUnpublishedOfferReportRequest {\n");

        sb.append("    format: ").append(toIndentedString(format)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

