/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Periods
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Periods {
    @SerializedName("period")
    private OfferInsightsPeriod period = null;

    @SerializedName("total")
    private Double total = null;

    @SerializedName("countries")
    private List<OfferInsightsCountry> countries = null;

    public Periods period(OfferInsightsPeriod period) {
        this.period = period;
        return this;
    }

    /**
     * Get period
     *
     * @return period
     **/
    @ApiModelProperty(required = true, value = "")
    public OfferInsightsPeriod getPeriod() {
        return period;
    }

    public void setPeriod(OfferInsightsPeriod period) {
        this.period = period;
    }

    public Periods total(Double total) {
        this.total = total;
        return this;
    }

    /**
     * Total number of customer visits on the product page when the offer had the buy box over the requested period (excluding the current day).
     *
     * @return total
     **/
    @ApiModelProperty(example = "50.0", value = "Total number of customer visits on the product page when the offer had the buy box over the requested period (excluding the current day).")
    public Double getTotal() {
        return total;
    }

    public void setTotal(Double total) {
        this.total = total;
    }

    public Periods countries(List<OfferInsightsCountry> countries) {
        this.countries = countries;
        return this;
    }

    public Periods addCountriesItem(OfferInsightsCountry countriesItem) {
        if (this.countries == null) {
            this.countries = new ArrayList<OfferInsightsCountry>();
        }
        this.countries.add(countriesItem);
        return this;
    }

    /**
     * Get countries
     *
     * @return countries
     **/
    @ApiModelProperty(value = "")
    public List<OfferInsightsCountry> getCountries() {
        return countries;
    }

    public void setCountries(List<OfferInsightsCountry> countries) {
        this.countries = countries;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Periods periods = (Periods) o;
        return Objects.equals(this.period, periods.period) &&
                Objects.equals(this.total, periods.total) &&
                Objects.equals(this.countries, periods.countries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(period, total, countries);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Periods {\n");

        sb.append("    period: ").append(toIndentedString(period)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

