/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * ProductLabelsProduct
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ProductLabelsProduct {
    @SerializedName("ean")
    private String ean = null;

    @SerializedName("quantity")
    private Integer quantity = null;

    public ProductLabelsProduct ean(String ean) {
        this.ean = ean;
        return this;
    }

    /**
     * The EAN number associated with this product.
     *
     * @return ean
     **/
    @ApiModelProperty(example = "0000007740404", value = "The EAN number associated with this product.")
    public String getEan() {
        return ean;
    }

    public void setEan(String ean) {
        this.ean = ean;
    }

    public ProductLabelsProduct quantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * The number of products to generate labels for.
     * minimum: 1
     * maximum: 9999
     *
     * @return quantity
     **/
    @ApiModelProperty(example = "1", required = true, value = "The number of products to generate labels for.")
    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProductLabelsProduct productLabelsProduct = (ProductLabelsProduct) o;
        return Objects.equals(this.ean, productLabelsProduct.ean) &&
                Objects.equals(this.quantity, productLabelsProduct.quantity);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ean, quantity);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProductLabelsProduct {\n");

        sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
        sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

