/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ReducedReplenishment
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ReducedReplenishment {
    @SerializedName("replenishmentId")
    private String replenishmentId = null;

    @SerializedName("reference")
    private String reference = null;

    @SerializedName("creationDateTime")
    private OffsetDateTime creationDateTime = null;

    @SerializedName("lines")
    private List<ReducedReplenishmentLines> lines = new ArrayList<ReducedReplenishmentLines>();

    @SerializedName("invalidLines")
    private List<ReducedInvalidReplenishmentLine> invalidLines = new ArrayList<ReducedInvalidReplenishmentLine>();

    public ReducedReplenishment replenishmentId(String replenishmentId) {
        this.replenishmentId = replenishmentId;
        return this;
    }

    /**
     * The unique identifier of the replenishment.
     *
     * @return replenishmentId
     **/
    @ApiModelProperty(example = "2312078154", required = true, value = "The unique identifier of the replenishment.")
    public String getReplenishmentId() {
        return replenishmentId;
    }

    public void setReplenishmentId(String replenishmentId) {
        this.replenishmentId = replenishmentId;
    }

    public ReducedReplenishment reference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * Custom user defined reference to identify the replenishment.
     *
     * @return reference
     **/
    @ApiModelProperty(example = "REFERENCE1", required = true, value = "Custom user defined reference to identify the replenishment.")
    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public ReducedReplenishment creationDateTime(OffsetDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
        return this;
    }

    /**
     * The date and time when this replenishment was created. In ISO 8601 format.
     *
     * @return creationDateTime
     **/
    @ApiModelProperty(example = "2020-09-09T16:44:03+02:00", required = true, value = "The date and time when this replenishment was created. In ISO 8601 format.")
    public OffsetDateTime getCreationDateTime() {
        return creationDateTime;
    }

    public void setCreationDateTime(OffsetDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
    }

    public ReducedReplenishment lines(List<ReducedReplenishmentLines> lines) {
        this.lines = lines;
        return this;
    }

    public ReducedReplenishment addLinesItem(ReducedReplenishmentLines linesItem) {
        this.lines.add(linesItem);
        return this;
    }

    /**
     * Get lines
     *
     * @return lines
     **/
    @ApiModelProperty(required = true, value = "")
    public List<ReducedReplenishmentLines> getLines() {
        return lines;
    }

    public void setLines(List<ReducedReplenishmentLines> lines) {
        this.lines = lines;
    }

    public ReducedReplenishment invalidLines(List<ReducedInvalidReplenishmentLine> invalidLines) {
        this.invalidLines = invalidLines;
        return this;
    }

    public ReducedReplenishment addInvalidLinesItem(ReducedInvalidReplenishmentLine invalidLinesItem) {
        this.invalidLines.add(invalidLinesItem);
        return this;
    }

    /**
     * Get invalidLines
     *
     * @return invalidLines
     **/
    @ApiModelProperty(required = true, value = "")
    public List<ReducedInvalidReplenishmentLine> getInvalidLines() {
        return invalidLines;
    }

    public void setInvalidLines(List<ReducedInvalidReplenishmentLine> invalidLines) {
        this.invalidLines = invalidLines;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReducedReplenishment reducedReplenishment = (ReducedReplenishment) o;
        return Objects.equals(this.replenishmentId, reducedReplenishment.replenishmentId) &&
                Objects.equals(this.reference, reducedReplenishment.reference) &&
                Objects.equals(this.creationDateTime, reducedReplenishment.creationDateTime) &&
                Objects.equals(this.lines, reducedReplenishment.lines) &&
                Objects.equals(this.invalidLines, reducedReplenishment.invalidLines);
    }

    @Override
    public int hashCode() {
        return Objects.hash(replenishmentId, reference, creationDateTime, lines, invalidLines);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReducedReplenishment {\n");

        sb.append("    replenishmentId: ").append(toIndentedString(replenishmentId)).append("\n");
        sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
        sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
        sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
        sb.append("    invalidLines: ").append(toIndentedString(invalidLines)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

