/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * RelatedSearchTerm
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class RelatedSearchTerm {
    @SerializedName("total")
    private Integer total = null;

    @SerializedName("searchTerm")
    private String searchTerm = null;

    public RelatedSearchTerm total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * The number of customer visits on the search page.
     *
     * @return total
     **/
    @ApiModelProperty(example = "100", required = true, value = "The number of customer visits on the search page.")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public RelatedSearchTerm searchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
        return this;
    }

    /**
     * The search term for which you requested the search volume.
     *
     * @return searchTerm
     **/
    @ApiModelProperty(example = "book", required = true, value = "The search term for which you requested the search volume.")
    public String getSearchTerm() {
        return searchTerm;
    }

    public void setSearchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RelatedSearchTerm relatedSearchTerm = (RelatedSearchTerm) o;
        return Objects.equals(this.total, relatedSearchTerm.total) &&
                Objects.equals(this.searchTerm, relatedSearchTerm.searchTerm);
    }

    @Override
    public int hashCode() {
        return Objects.hash(total, searchTerm);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RelatedSearchTerm {\n");

        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    searchTerm: ").append(toIndentedString(searchTerm)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

