/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SalesForecastResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class SalesForecastResponse {
    @SerializedName("name")
    private String name = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("total")
    private Total total = null;

    @SerializedName("countries")
    private List<Countries> countries = new ArrayList<Countries>();

    @SerializedName("periods")
    private List<SalesForecastPeriod> periods = new ArrayList<SalesForecastPeriod>();

    public SalesForecastResponse name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Indicator name.
     *
     * @return name
     **/
    @ApiModelProperty(example = "SALES_FORECAST", required = true, value = "Indicator name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SalesForecastResponse type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Interpretation of the data that applies to this measurement.
     *
     * @return type
     **/
    @ApiModelProperty(example = "DECIMAL", required = true, value = "Interpretation of the data that applies to this measurement.")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public SalesForecastResponse total(Total total) {
        this.total = total;
        return this;
    }

    /**
     * Get total
     *
     * @return total
     **/
    @ApiModelProperty(required = true, value = "")
    public Total getTotal() {
        return total;
    }

    public void setTotal(Total total) {
        this.total = total;
    }

    public SalesForecastResponse countries(List<Countries> countries) {
        this.countries = countries;
        return this;
    }

    public SalesForecastResponse addCountriesItem(Countries countriesItem) {
        this.countries.add(countriesItem);
        return this;
    }

    /**
     * Get countries
     *
     * @return countries
     **/
    @ApiModelProperty(required = true, value = "")
    public List<Countries> getCountries() {
        return countries;
    }

    public void setCountries(List<Countries> countries) {
        this.countries = countries;
    }

    public SalesForecastResponse periods(List<SalesForecastPeriod> periods) {
        this.periods = periods;
        return this;
    }

    public SalesForecastResponse addPeriodsItem(SalesForecastPeriod periodsItem) {
        this.periods.add(periodsItem);
        return this;
    }

    /**
     * Get periods
     *
     * @return periods
     **/
    @ApiModelProperty(required = true, value = "")
    public List<SalesForecastPeriod> getPeriods() {
        return periods;
    }

    public void setPeriods(List<SalesForecastPeriod> periods) {
        this.periods = periods;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SalesForecastResponse salesForecastResponse = (SalesForecastResponse) o;
        return Objects.equals(this.name, salesForecastResponse.name) &&
                Objects.equals(this.type, salesForecastResponse.type) &&
                Objects.equals(this.total, salesForecastResponse.total) &&
                Objects.equals(this.countries, salesForecastResponse.countries) &&
                Objects.equals(this.periods, salesForecastResponse.periods);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, type, total, countries, periods);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SalesForecastResponse {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
        sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

