/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SalesForecastPeriod
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class SalesForecastPeriod {
    @SerializedName("weeksAhead")
    private Integer weeksAhead = null;

    @SerializedName("total")
    private Total total = null;

    @SerializedName("countries")
    private List<Countries> countries = new ArrayList<Countries>();

    public SalesForecastPeriod weeksAhead(Integer weeksAhead) {
        this.weeksAhead = weeksAhead;
        return this;
    }

    /**
     * The number of weeks into the future, starting from today.
     *
     * @return weeksAhead
     **/
    @ApiModelProperty(example = "2", required = true, value = "The number of weeks into the future, starting from today.")
    public Integer getWeeksAhead() {
        return weeksAhead;
    }

    public void setWeeksAhead(Integer weeksAhead) {
        this.weeksAhead = weeksAhead;
    }

    public SalesForecastPeriod total(Total total) {
        this.total = total;
        return this;
    }

    /**
     * Get total
     *
     * @return total
     **/
    @ApiModelProperty(required = true, value = "")
    public Total getTotal() {
        return total;
    }

    public void setTotal(Total total) {
        this.total = total;
    }

    public SalesForecastPeriod countries(List<Countries> countries) {
        this.countries = countries;
        return this;
    }

    public SalesForecastPeriod addCountriesItem(Countries countriesItem) {
        this.countries.add(countriesItem);
        return this;
    }

    /**
     * Get countries
     *
     * @return countries
     **/
    @ApiModelProperty(required = true, value = "")
    public List<Countries> getCountries() {
        return countries;
    }

    public void setCountries(List<Countries> countries) {
        this.countries = countries;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SalesForecastPeriod salesForecastPeriod = (SalesForecastPeriod) o;
        return Objects.equals(this.weeksAhead, salesForecastPeriod.weeksAhead) &&
                Objects.equals(this.total, salesForecastPeriod.total) &&
                Objects.equals(this.countries, salesForecastPeriod.countries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(weeksAhead, total, countries);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SalesForecastPeriod {\n");

        sb.append("    weeksAhead: ").append(toIndentedString(weeksAhead)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

