/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SearchTerm
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class SearchTerm {
    @SerializedName("searchTerm")
    private String searchTerm = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("total")
    private Integer total = null;

    @SerializedName("countries")
    private List<SearchTermsCountry> countries = new ArrayList<SearchTermsCountry>();

    @SerializedName("periods")
    private List<TotalPeriod> periods = new ArrayList<TotalPeriod>();

    @SerializedName("relatedSearchTerms")
    private List<RelatedSearchTerm> relatedSearchTerms = null;

    public SearchTerm searchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
        return this;
    }

    /**
     * The search term for which you requested the search volume.
     *
     * @return searchTerm
     **/
    @ApiModelProperty(example = "book", required = true, value = "The search term for which you requested the search volume.")
    public String getSearchTerm() {
        return searchTerm;
    }

    public void setSearchTerm(String searchTerm) {
        this.searchTerm = searchTerm;
    }

    public SearchTerm type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Interpretation of the data that applies to this measurement.
     *
     * @return type
     **/
    @ApiModelProperty(example = "count", required = true, value = "Interpretation of the data that applies to this measurement.")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public SearchTerm total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * The number of customer visits on the search page.
     *
     * @return total
     **/
    @ApiModelProperty(example = "100", required = true, value = "The number of customer visits on the search page.")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public SearchTerm countries(List<SearchTermsCountry> countries) {
        this.countries = countries;
        return this;
    }

    public SearchTerm addCountriesItem(SearchTermsCountry countriesItem) {
        this.countries.add(countriesItem);
        return this;
    }

    /**
     * Get countries
     *
     * @return countries
     **/
    @ApiModelProperty(required = true, value = "")
    public List<SearchTermsCountry> getCountries() {
        return countries;
    }

    public void setCountries(List<SearchTermsCountry> countries) {
        this.countries = countries;
    }

    public SearchTerm periods(List<TotalPeriod> periods) {
        this.periods = periods;
        return this;
    }

    public SearchTerm addPeriodsItem(TotalPeriod periodsItem) {
        this.periods.add(periodsItem);
        return this;
    }

    /**
     * Get periods
     *
     * @return periods
     **/
    @ApiModelProperty(required = true, value = "")
    public List<TotalPeriod> getPeriods() {
        return periods;
    }

    public void setPeriods(List<TotalPeriod> periods) {
        this.periods = periods;
    }

    public SearchTerm relatedSearchTerms(List<RelatedSearchTerm> relatedSearchTerms) {
        this.relatedSearchTerms = relatedSearchTerms;
        return this;
    }

    public SearchTerm addRelatedSearchTermsItem(RelatedSearchTerm relatedSearchTermsItem) {
        if (this.relatedSearchTerms == null) {
            this.relatedSearchTerms = new ArrayList<RelatedSearchTerm>();
        }
        this.relatedSearchTerms.add(relatedSearchTermsItem);
        return this;
    }

    /**
     * Get relatedSearchTerms
     *
     * @return relatedSearchTerms
     **/
    @ApiModelProperty(value = "")
    public List<RelatedSearchTerm> getRelatedSearchTerms() {
        return relatedSearchTerms;
    }

    public void setRelatedSearchTerms(List<RelatedSearchTerm> relatedSearchTerms) {
        this.relatedSearchTerms = relatedSearchTerms;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchTerm searchTerm = (SearchTerm) o;
        return Objects.equals(this.searchTerm, searchTerm.searchTerm) &&
                Objects.equals(this.type, searchTerm.type) &&
                Objects.equals(this.total, searchTerm.total) &&
                Objects.equals(this.countries, searchTerm.countries) &&
                Objects.equals(this.periods, searchTerm.periods) &&
                Objects.equals(this.relatedSearchTerms, searchTerm.relatedSearchTerms);
    }

    @Override
    public int hashCode() {
        return Objects.hash(searchTerm, type, total, countries, periods, relatedSearchTerms);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchTerm {\n");

        sb.append("    searchTerm: ").append(toIndentedString(searchTerm)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
        sb.append("    periods: ").append(toIndentedString(periods)).append("\n");
        sb.append("    relatedSearchTerms: ").append(toIndentedString(relatedSearchTerms)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

