/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ShipmentTransport
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ShipmentTransport {
    @SerializedName("transportId")
    private String transportId = null;

    @SerializedName("transporterCode")
    private String transporterCode = null;

    @SerializedName("trackAndTrace")
    private String trackAndTrace = null;

    @SerializedName("shippingLabelId")
    private String shippingLabelId = null;

    @SerializedName("transportEvents")
    private List<TransportEvent> transportEvents = null;

    public ShipmentTransport transportId(String transportId) {
        this.transportId = transportId;
        return this;
    }

    /**
     * The transport id.
     *
     * @return transportId
     **/
    @ApiModelProperty(example = "312778947", value = "The transport id.")
    public String getTransportId() {
        return transportId;
    }

    public void setTransportId(String transportId) {
        this.transportId = transportId;
    }

    public ShipmentTransport transporterCode(String transporterCode) {
        this.transporterCode = transporterCode;
        return this;
    }

    /**
     * Specify the transporter that will carry out the shipment.
     *
     * @return transporterCode
     **/
    @ApiModelProperty(example = "TNT", value = "Specify the transporter that will carry out the shipment.")
    public String getTransporterCode() {
        return transporterCode;
    }

    public void setTransporterCode(String transporterCode) {
        this.transporterCode = transporterCode;
    }

    public ShipmentTransport trackAndTrace(String trackAndTrace) {
        this.trackAndTrace = trackAndTrace;
        return this;
    }

    /**
     * The track and trace code that is associated with this transport.
     *
     * @return trackAndTrace
     **/
    @ApiModelProperty(example = "3SBOL0987654321", value = "The track and trace code that is associated with this transport.")
    public String getTrackAndTrace() {
        return trackAndTrace;
    }

    public void setTrackAndTrace(String trackAndTrace) {
        this.trackAndTrace = trackAndTrace;
    }

    public ShipmentTransport shippingLabelId(String shippingLabelId) {
        this.shippingLabelId = shippingLabelId;
        return this;
    }

    /**
     * The shipping label id.
     *
     * @return shippingLabelId
     **/
    @ApiModelProperty(example = "123456789", value = "The shipping label id.")
    public String getShippingLabelId() {
        return shippingLabelId;
    }

    public void setShippingLabelId(String shippingLabelId) {
        this.shippingLabelId = shippingLabelId;
    }

    public ShipmentTransport transportEvents(List<TransportEvent> transportEvents) {
        this.transportEvents = transportEvents;
        return this;
    }

    public ShipmentTransport addTransportEventsItem(TransportEvent transportEventsItem) {
        if (this.transportEvents == null) {
            this.transportEvents = new ArrayList<TransportEvent>();
        }
        this.transportEvents.add(transportEventsItem);
        return this;
    }

    /**
     * Get transportEvents
     *
     * @return transportEvents
     **/
    @ApiModelProperty(value = "")
    public List<TransportEvent> getTransportEvents() {
        return transportEvents;
    }

    public void setTransportEvents(List<TransportEvent> transportEvents) {
        this.transportEvents = transportEvents;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentTransport shipmentTransport = (ShipmentTransport) o;
        return Objects.equals(this.transportId, shipmentTransport.transportId) &&
                Objects.equals(this.transporterCode, shipmentTransport.transporterCode) &&
                Objects.equals(this.trackAndTrace, shipmentTransport.trackAndTrace) &&
                Objects.equals(this.shippingLabelId, shipmentTransport.shippingLabelId) &&
                Objects.equals(this.transportEvents, shipmentTransport.transportEvents);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transportId, transporterCode, trackAndTrace, shippingLabelId, transportEvents);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ShipmentTransport {\n");

        sb.append("    transportId: ").append(toIndentedString(transportId)).append("\n");
        sb.append("    transporterCode: ").append(toIndentedString(transporterCode)).append("\n");
        sb.append("    trackAndTrace: ").append(toIndentedString(trackAndTrace)).append("\n");
        sb.append("    shippingLabelId: ").append(toIndentedString(shippingLabelId)).append("\n");
        sb.append("    transportEvents: ").append(toIndentedString(transportEvents)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

