/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * The address details where this order needs to be shipped to. This can be the customers&#39; own address, a (company) business address or a Pick Up Point address.
 */
@ApiModel(description = "The address details where this order needs to be shipped to. This can be the customers' own address, a (company) business address or a Pick Up Point address.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ShipmentDetails {
    @SerializedName("pickupPointName")
    private String pickupPointName = null;

    /**
     * The salutation of the customer.
     */
    @JsonAdapter(SalutationEnum.Adapter.class)
    public enum SalutationEnum {
        MALE("MALE"),

        FEMALE("FEMALE"),

        UNKNOWN("UNKNOWN");

        private String value;

        SalutationEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SalutationEnum fromValue(String text) {
            for (SalutationEnum b : SalutationEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<SalutationEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SalutationEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SalutationEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return SalutationEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("salutation")
    private SalutationEnum salutation = null;

    @SerializedName("firstName")
    private String firstName = null;

    @SerializedName("surname")
    private String surname = null;

    @SerializedName("streetName")
    private String streetName = null;

    @SerializedName("houseNumber")
    private String houseNumber = null;

    @SerializedName("houseNumberExtension")
    private String houseNumberExtension = null;

    @SerializedName("extraAddressInformation")
    private String extraAddressInformation = null;

    @SerializedName("zipCode")
    private String zipCode = null;

    @SerializedName("city")
    private String city = null;

    @SerializedName("countryCode")
    private String countryCode = null;

    @SerializedName("email")
    private String email = null;

    @SerializedName("company")
    private String company = null;

    @SerializedName("deliveryPhoneNumber")
    private String deliveryPhoneNumber = null;

    /**
     * The language of the customer in case of contact.
     */
    @JsonAdapter(LanguageEnum.Adapter.class)
    public enum LanguageEnum {
        NL("nl"),

        NL_BE("nl-BE"),

        FR("fr"),

        FR_BE("fr-BE");

        private String value;

        LanguageEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static LanguageEnum fromValue(String text) {
            for (LanguageEnum b : LanguageEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<LanguageEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public LanguageEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return LanguageEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("language")
    private LanguageEnum language = null;

    public ShipmentDetails pickupPointName(String pickupPointName) {
        this.pickupPointName = pickupPointName;
        return this;
    }

    /**
     * The name of Pick Up Point location this order needs to be shipped to.
     *
     * @return pickupPointName
     **/
    @ApiModelProperty(example = "Albert Heijn: UTRECHT", value = "The name of Pick Up Point location this order needs to be shipped to.")
    public String getPickupPointName() {
        return pickupPointName;
    }

    public void setPickupPointName(String pickupPointName) {
        this.pickupPointName = pickupPointName;
    }

    public ShipmentDetails salutation(SalutationEnum salutation) {
        this.salutation = salutation;
        return this;
    }

    /**
     * The salutation of the customer.
     *
     * @return salutation
     **/
    @ApiModelProperty(example = "MALE", value = "The salutation of the customer.")
    public SalutationEnum getSalutation() {
        return salutation;
    }

    public void setSalutation(SalutationEnum salutation) {
        this.salutation = salutation;
    }

    public ShipmentDetails firstName(String firstName) {
        this.firstName = firstName;
        return this;
    }

    /**
     * The first name of the customer.
     *
     * @return firstName
     **/
    @ApiModelProperty(example = "Billie", value = "The first name of the customer.")
    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public ShipmentDetails surname(String surname) {
        this.surname = surname;
        return this;
    }

    /**
     * The surname of the customer.
     *
     * @return surname
     **/
    @ApiModelProperty(example = "Jansen", value = "The surname of the customer.")
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public ShipmentDetails streetName(String streetName) {
        this.streetName = streetName;
        return this;
    }

    /**
     * The street name.
     *
     * @return streetName
     **/
    @ApiModelProperty(example = "Dorpstraat", value = "The street name.")
    public String getStreetName() {
        return streetName;
    }

    public void setStreetName(String streetName) {
        this.streetName = streetName;
    }

    public ShipmentDetails houseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
        return this;
    }

    /**
     * The house number.
     *
     * @return houseNumber
     **/
    @ApiModelProperty(example = "1", value = "The house number.")
    public String getHouseNumber() {
        return houseNumber;
    }

    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber;
    }

    public ShipmentDetails houseNumberExtension(String houseNumberExtension) {
        this.houseNumberExtension = houseNumberExtension;
        return this;
    }

    /**
     * The extension on the house number.
     *
     * @return houseNumberExtension
     **/
    @ApiModelProperty(example = "B", value = "The extension on the house number.")
    public String getHouseNumberExtension() {
        return houseNumberExtension;
    }

    public void setHouseNumberExtension(String houseNumberExtension) {
        this.houseNumberExtension = houseNumberExtension;
    }

    public ShipmentDetails extraAddressInformation(String extraAddressInformation) {
        this.extraAddressInformation = extraAddressInformation;
        return this;
    }

    /**
     * Additional information related to the address that helps in delivering the package.
     *
     * @return extraAddressInformation
     **/
    @ApiModelProperty(example = "Apartment", value = "Additional information related to the address that helps in delivering the package.")
    public String getExtraAddressInformation() {
        return extraAddressInformation;
    }

    public void setExtraAddressInformation(String extraAddressInformation) {
        this.extraAddressInformation = extraAddressInformation;
    }

    public ShipmentDetails zipCode(String zipCode) {
        this.zipCode = zipCode;
        return this;
    }

    /**
     * The ZIP code in &#39;1234AB&#39; format for NL orders and &#39;0000&#39; format for BE orders.
     *
     * @return zipCode
     **/
    @ApiModelProperty(example = "1111ZZ", value = "The ZIP code in '1234AB' format for NL orders and '0000' format for BE orders.")
    public String getZipCode() {
        return zipCode;
    }

    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    public ShipmentDetails city(String city) {
        this.city = city;
        return this;
    }

    /**
     * The name of the city.
     *
     * @return city
     **/
    @ApiModelProperty(example = "Utrecht", value = "The name of the city.")
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public ShipmentDetails countryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }

    /**
     * The country code.
     *
     * @return countryCode
     **/
    @ApiModelProperty(example = "NL", value = "The country code.")
    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public ShipmentDetails email(String email) {
        this.email = email;
        return this;
    }

    /**
     * A scrambled email address that can be used to contact the customer.
     *
     * @return email
     **/
    @ApiModelProperty(example = "billie@verkopen.bol.com", value = "A scrambled email address that can be used to contact the customer.")
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public ShipmentDetails company(String company) {
        this.company = company;
        return this;
    }

    /**
     * The company name.
     *
     * @return company
     **/
    @ApiModelProperty(example = "bol.com", value = "The company name.")
    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public ShipmentDetails deliveryPhoneNumber(String deliveryPhoneNumber) {
        this.deliveryPhoneNumber = deliveryPhoneNumber;
        return this;
    }

    /**
     * The delivery phone number of the customer. Filled in case the order requires an appointment for delivering the goods.
     *
     * @return deliveryPhoneNumber
     **/
    @ApiModelProperty(example = "012123456", value = "The delivery phone number of the customer. Filled in case the order requires an appointment for delivering the goods.")
    public String getDeliveryPhoneNumber() {
        return deliveryPhoneNumber;
    }

    public void setDeliveryPhoneNumber(String deliveryPhoneNumber) {
        this.deliveryPhoneNumber = deliveryPhoneNumber;
    }

    public ShipmentDetails language(LanguageEnum language) {
        this.language = language;
        return this;
    }

    /**
     * The language of the customer in case of contact.
     *
     * @return language
     **/
    @ApiModelProperty(example = "nl", value = "The language of the customer in case of contact.")
    public LanguageEnum getLanguage() {
        return language;
    }

    public void setLanguage(LanguageEnum language) {
        this.language = language;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentDetails shipmentDetails = (ShipmentDetails) o;
        return Objects.equals(this.pickupPointName, shipmentDetails.pickupPointName) &&
                Objects.equals(this.salutation, shipmentDetails.salutation) &&
                Objects.equals(this.firstName, shipmentDetails.firstName) &&
                Objects.equals(this.surname, shipmentDetails.surname) &&
                Objects.equals(this.streetName, shipmentDetails.streetName) &&
                Objects.equals(this.houseNumber, shipmentDetails.houseNumber) &&
                Objects.equals(this.houseNumberExtension, shipmentDetails.houseNumberExtension) &&
                Objects.equals(this.extraAddressInformation, shipmentDetails.extraAddressInformation) &&
                Objects.equals(this.zipCode, shipmentDetails.zipCode) &&
                Objects.equals(this.city, shipmentDetails.city) &&
                Objects.equals(this.countryCode, shipmentDetails.countryCode) &&
                Objects.equals(this.email, shipmentDetails.email) &&
                Objects.equals(this.company, shipmentDetails.company) &&
                Objects.equals(this.deliveryPhoneNumber, shipmentDetails.deliveryPhoneNumber) &&
                Objects.equals(this.language, shipmentDetails.language);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pickupPointName, salutation, firstName, surname, streetName, houseNumber, houseNumberExtension, extraAddressInformation, zipCode, city, countryCode, email, company, deliveryPhoneNumber, language);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ShipmentDetails {\n");

        sb.append("    pickupPointName: ").append(toIndentedString(pickupPointName)).append("\n");
        sb.append("    salutation: ").append(toIndentedString(salutation)).append("\n");
        sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
        sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
        sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
        sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
        sb.append("    houseNumberExtension: ").append(toIndentedString(houseNumberExtension)).append("\n");
        sb.append("    extraAddressInformation: ").append(toIndentedString(extraAddressInformation)).append("\n");
        sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
        sb.append("    city: ").append(toIndentedString(city)).append("\n");
        sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
        sb.append("    email: ").append(toIndentedString(email)).append("\n");
        sb.append("    company: ").append(toIndentedString(company)).append("\n");
        sb.append("    deliveryPhoneNumber: ").append(toIndentedString(deliveryPhoneNumber)).append("\n");
        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

