/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * UpdateOfferPriceRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class UpdateOfferPriceRequest {
    @SerializedName("pricing")
    private Pricing pricing = null;

    public UpdateOfferPriceRequest pricing(Pricing pricing) {
        this.pricing = pricing;
        return this;
    }

    /**
     * Get pricing
     *
     * @return pricing
     **/
    @ApiModelProperty(required = true, value = "")
    public Pricing getPricing() {
        return pricing;
    }

    public void setPricing(Pricing pricing) {
        this.pricing = pricing;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateOfferPriceRequest updateOfferPriceRequest = (UpdateOfferPriceRequest) o;
        return Objects.equals(this.pricing, updateOfferPriceRequest.pricing);
    }

    @Override
    public int hashCode() {
        return Objects.hash(pricing);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UpdateOfferPriceRequest {\n");

        sb.append("    pricing: ").append(toIndentedString(pricing)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

