/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package be.datafarmhouse.bol.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Describes a violation that occurred interacting with the API.
 */
@ApiModel(description = "Describes a violation that occurred interacting with the API.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Violation {
    @SerializedName("name")
    private String name = null;

    @SerializedName("reason")
    private String reason = null;

    public Violation name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Describes the origin of the error, for instance a field or query parameter validation error.
     *
     * @return name
     **/
    @ApiModelProperty(example = "exampleValue", value = "Describes the origin of the error, for instance a field or query parameter validation error.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Violation reason(String reason) {
        this.reason = reason;
        return this;
    }

    /**
     * Detailed description of the validation error that caused the problem.
     *
     * @return reason
     **/
    @ApiModelProperty(example = "Request contains invalid value(s): 'INVALID', allowed values: ALLOWED_VALUE1, ALLOWED_VALUE2.", value = "Detailed description of the validation error that caused the problem.")
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Violation violation = (Violation) o;
        return Objects.equals(this.name, violation.name) &&
                Objects.equals(this.reason, violation.reason);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, reason);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Violation {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

