/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AdditionalService
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class AdditionalService {
    @SerializedName("serviceType")
    private String serviceType = null;

    public AdditionalService serviceType(String serviceType) {
        this.serviceType = serviceType;
        return this;
    }

    /**
     * An additional service type that the customer selected when purchasing this order item.
     *
     * @return serviceType
     **/
    @ApiModelProperty(example = "PLACEMENT_AND_INSTALLATION", value = "An additional service type that the customer selected when purchasing this order item.")
    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AdditionalService additionalService = (AdditionalService) o;
        return Objects.equals(this.serviceType, additionalService.serviceType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(serviceType);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class AdditionalService {\n");

        sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

