/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BulkCommissionRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class BulkCommissionRequest {
    @SerializedName("commissionQueries")
    private List<BulkCommissionQuery> commissionQueries = new ArrayList<BulkCommissionQuery>();

    public BulkCommissionRequest commissionQueries(List<BulkCommissionQuery> commissionQueries) {
        this.commissionQueries = commissionQueries;
        return this;
    }

    public BulkCommissionRequest addCommissionQueriesItem(BulkCommissionQuery commissionQueriesItem) {
        this.commissionQueries.add(commissionQueriesItem);
        return this;
    }

    /**
     * Get commissionQueries
     *
     * @return commissionQueries
     **/
    @ApiModelProperty(required = true, value = "")
    public List<BulkCommissionQuery> getCommissionQueries() {
        return commissionQueries;
    }

    public void setCommissionQueries(List<BulkCommissionQuery> commissionQueries) {
        this.commissionQueries = commissionQueries;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BulkCommissionRequest bulkCommissionRequest = (BulkCommissionRequest) o;
        return Objects.equals(this.commissionQueries, bulkCommissionRequest.commissionQueries);
    }

    @Override
    public int hashCode() {
        return Objects.hash(commissionQueries);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BulkCommissionRequest {\n");

        sb.append("    commissionQueries: ").append(toIndentedString(commissionQueries)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

