/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.util.Objects;

/**
 * Campaign
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Campaign {
    @SerializedName("name")
    private String name = null;

    @SerializedName("startDateTime")
    private OffsetDateTime startDateTime = null;

    @SerializedName("endDateTime")
    private OffsetDateTime endDateTime = null;

    public Campaign name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The name of the campaign under which the promotion had been created.
     *
     * @return name
     **/
    @ApiModelProperty(example = "Campaign name", required = true, value = "The name of the campaign under which the promotion had been created.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Campaign startDateTime(OffsetDateTime startDateTime) {
        this.startDateTime = startDateTime;
        return this;
    }

    /**
     * The starting date and time of the campaign.
     *
     * @return startDateTime
     **/
    @ApiModelProperty(example = "2021-03-29T00:00:00.000+02:00", required = true, value = "The starting date and time of the campaign.")
    public OffsetDateTime getStartDateTime() {
        return startDateTime;
    }

    public void setStartDateTime(OffsetDateTime startDateTime) {
        this.startDateTime = startDateTime;
    }

    public Campaign endDateTime(OffsetDateTime endDateTime) {
        this.endDateTime = endDateTime;
        return this;
    }

    /**
     * The ending date and time of the campaign.
     *
     * @return endDateTime
     **/
    @ApiModelProperty(example = "2021-05-10T00:00:00.000+02:00", value = "The ending date and time of the campaign.")
    public OffsetDateTime getEndDateTime() {
        return endDateTime;
    }

    public void setEndDateTime(OffsetDateTime endDateTime) {
        this.endDateTime = endDateTime;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Campaign campaign = (Campaign) o;
        return Objects.equals(this.name, campaign.name) &&
                Objects.equals(this.startDateTime, campaign.startDateTime) &&
                Objects.equals(this.endDateTime, campaign.endDateTime);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, startDateTime, endDateTime);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Campaign {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    startDateTime: ").append(toIndentedString(startDateTime)).append("\n");
        sb.append("    endDateTime: ").append(toIndentedString(endDateTime)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

