/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Countries
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Countries {
    @SerializedName("countryCode")
    private String countryCode = null;

    @SerializedName("minimum")
    private Double minimum = null;

    @SerializedName("maximum")
    private Double maximum = null;

    public Countries countryCode(String countryCode) {
        this.countryCode = countryCode;
        return this;
    }

    /**
     * Countries in which this offer is currently on sale in the webshop, in ISO-3166-1 format.
     *
     * @return countryCode
     **/
    @ApiModelProperty(example = "NL", value = "Countries in which this offer is currently on sale in the webshop, in ISO-3166-1 format.")
    public String getCountryCode() {
        return countryCode;
    }

    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    public Countries minimum(Double minimum) {
        this.minimum = minimum;
        return this;
    }

    /**
     * Minimum number of estimated sales expectations on the bol.com platform.
     *
     * @return minimum
     **/
    @ApiModelProperty(example = "10.5", required = true, value = "Minimum number of estimated sales expectations on the bol.com platform.")
    public Double getMinimum() {
        return minimum;
    }

    public void setMinimum(Double minimum) {
        this.minimum = minimum;
    }

    public Countries maximum(Double maximum) {
        this.maximum = maximum;
        return this;
    }

    /**
     * Maximum number of estimated sales expectations on the bol.com platform.
     *
     * @return maximum
     **/
    @ApiModelProperty(example = "20.5", required = true, value = "Maximum number of estimated sales expectations on the bol.com platform.")
    public Double getMaximum() {
        return maximum;
    }

    public void setMaximum(Double maximum) {
        this.maximum = maximum;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Countries countries = (Countries) o;
        return Objects.equals(this.countryCode, countries.countryCode) &&
                Objects.equals(this.minimum, countries.minimum) &&
                Objects.equals(this.maximum, countries.maximum);
    }

    @Override
    public int hashCode() {
        return Objects.hash(countryCode, minimum, maximum);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Countries {\n");

        sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
        sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
        sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

