/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CreateProductContentSingleRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class CreateProductContentSingleRequest {
    /**
     * The language in which content is submitted.
     */
    @JsonAdapter(LanguageEnum.Adapter.class)
    public enum LanguageEnum {
        NL("nl"),

        NL_BE("nl-BE"),

        FR("fr"),

        FR_BE("fr-BE");

        private String value;

        LanguageEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static LanguageEnum fromValue(String text) {
            for (LanguageEnum b : LanguageEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<LanguageEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public LanguageEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return LanguageEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("language")
    private LanguageEnum language = null;

    @SerializedName("attributes")
    private List<Attribute> attributes = new ArrayList<Attribute>();

    @SerializedName("assets")
    private List<Asset> assets = null;

    public CreateProductContentSingleRequest language(LanguageEnum language) {
        this.language = language;
        return this;
    }

    /**
     * The language in which content is submitted.
     *
     * @return language
     **/
    @ApiModelProperty(example = "nl", required = true, value = "The language in which content is submitted.")
    public LanguageEnum getLanguage() {
        return language;
    }

    public void setLanguage(LanguageEnum language) {
        this.language = language;
    }

    public CreateProductContentSingleRequest attributes(List<Attribute> attributes) {
        this.attributes = attributes;
        return this;
    }

    public CreateProductContentSingleRequest addAttributesItem(Attribute attributesItem) {
        this.attributes.add(attributesItem);
        return this;
    }

    /**
     * A list of attributes.
     *
     * @return attributes
     **/
    @ApiModelProperty(required = true, value = "A list of attributes.")
    public List<Attribute> getAttributes() {
        return attributes;
    }

    public void setAttributes(List<Attribute> attributes) {
        this.attributes = attributes;
    }

    public CreateProductContentSingleRequest assets(List<Asset> assets) {
        this.assets = assets;
        return this;
    }

    public CreateProductContentSingleRequest addAssetsItem(Asset assetsItem) {
        if (this.assets == null) {
            this.assets = new ArrayList<Asset>();
        }
        this.assets.add(assetsItem);
        return this;
    }

    /**
     * Get assets
     *
     * @return assets
     **/
    @ApiModelProperty(value = "")
    public List<Asset> getAssets() {
        return assets;
    }

    public void setAssets(List<Asset> assets) {
        this.assets = assets;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateProductContentSingleRequest createProductContentSingleRequest = (CreateProductContentSingleRequest) o;
        return Objects.equals(this.language, createProductContentSingleRequest.language) &&
                Objects.equals(this.attributes, createProductContentSingleRequest.attributes) &&
                Objects.equals(this.assets, createProductContentSingleRequest.assets);
    }

    @Override
    public int hashCode() {
        return Objects.hash(language, attributes, assets);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class CreateProductContentSingleRequest {\n");

        sb.append("    language: ").append(toIndentedString(language)).append("\n");
        sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
        sb.append("    assets: ").append(toIndentedString(assets)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

