/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Offer insights.
 */
@ApiModel(description = "Offer insights.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class OfferInsights {
    @SerializedName("offerInsights")
    private List<OfferInsight> offerInsights = new ArrayList<OfferInsight>();

    public OfferInsights offerInsights(List<OfferInsight> offerInsights) {
        this.offerInsights = offerInsights;
        return this;
    }

    public OfferInsights addOfferInsightsItem(OfferInsight offerInsightsItem) {
        this.offerInsights.add(offerInsightsItem);
        return this;
    }

    /**
     * Get offerInsights
     *
     * @return offerInsights
     **/
    @ApiModelProperty(required = true, value = "")
    public List<OfferInsight> getOfferInsights() {
        return offerInsights;
    }

    public void setOfferInsights(List<OfferInsight> offerInsights) {
        this.offerInsights = offerInsights;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OfferInsights offerInsights = (OfferInsights) o;
        return Objects.equals(this.offerInsights, offerInsights.offerInsights);
    }

    @Override
    public int hashCode() {
        return Objects.hash(offerInsights);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OfferInsights {\n");

        sb.append("    offerInsights: ").append(toIndentedString(offerInsights)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

