/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * OrderItemCancellation
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class OrderItemCancellation {
    @SerializedName("orderItemId")
    private String orderItemId = null;

    /**
     * The code representing the reason for cancellation of this item.
     */
    @JsonAdapter(ReasonCodeEnum.Adapter.class)
    public enum ReasonCodeEnum {
        OUT_OF_STOCK("OUT_OF_STOCK"),

        REQUESTED_BY_CUSTOMER("REQUESTED_BY_CUSTOMER"),

        BAD_CONDITION("BAD_CONDITION"),

        HIGHER_SHIPCOST("HIGHER_SHIPCOST"),

        INCORRECT_PRICE("INCORRECT_PRICE"),

        NOT_AVAIL_IN_TIME("NOT_AVAIL_IN_TIME"),

        NO_BOL_GUARANTEE("NO_BOL_GUARANTEE"),

        ORDERED_TWICE("ORDERED_TWICE"),

        RETAIN_ITEM("RETAIN_ITEM"),

        TECH_ISSUE("TECH_ISSUE"),

        UNFINDABLE_ITEM("UNFINDABLE_ITEM"),

        OTHER("OTHER");

        private String value;

        ReasonCodeEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static ReasonCodeEnum fromValue(String text) {
            for (ReasonCodeEnum b : ReasonCodeEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<ReasonCodeEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final ReasonCodeEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public ReasonCodeEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return ReasonCodeEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("reasonCode")
    private ReasonCodeEnum reasonCode = null;

    public OrderItemCancellation orderItemId(String orderItemId) {
        this.orderItemId = orderItemId;
        return this;
    }

    /**
     * The id for the order item. One order can have multiple order items, but the list can only take one item.
     *
     * @return orderItemId
     **/
    @ApiModelProperty(example = "2012345678", required = true, value = "The id for the order item. One order can have multiple order items, but the list can only take one item.")
    public String getOrderItemId() {
        return orderItemId;
    }

    public void setOrderItemId(String orderItemId) {
        this.orderItemId = orderItemId;
    }

    public OrderItemCancellation reasonCode(ReasonCodeEnum reasonCode) {
        this.reasonCode = reasonCode;
        return this;
    }

    /**
     * The code representing the reason for cancellation of this item.
     *
     * @return reasonCode
     **/
    @ApiModelProperty(example = "BAD_CONDITION", required = true, value = "The code representing the reason for cancellation of this item.")
    public ReasonCodeEnum getReasonCode() {
        return reasonCode;
    }

    public void setReasonCode(ReasonCodeEnum reasonCode) {
        this.reasonCode = reasonCode;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrderItemCancellation orderItemCancellation = (OrderItemCancellation) o;
        return Objects.equals(this.orderItemId, orderItemCancellation.orderItemId) &&
                Objects.equals(this.reasonCode, orderItemCancellation.reasonCode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(orderItemId, reasonCode);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OrderItemCancellation {\n");

        sb.append("    orderItemId: ").append(toIndentedString(orderItemId)).append("\n");
        sb.append("    reasonCode: ").append(toIndentedString(reasonCode)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

