/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Party
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Party {
    @SerializedName("name")
    private String name = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("role")
    private String role = null;

    public Party name(String name) {
        this.name = name;
        return this;
    }

    /**
     * The name of the party involved for this product.
     *
     * @return name
     **/
    @ApiModelProperty(example = "Maybelline", required = true, value = "The name of the party involved for this product.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Party type(String type) {
        this.type = type;
        return this;
    }

    /**
     * The type of party involved for this product.
     *
     * @return type
     **/
    @ApiModelProperty(example = "Brand", required = true, value = "The type of party involved for this product.")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Party role(String role) {
        this.role = role;
        return this;
    }

    /**
     * The role of the party involved for this product.
     *
     * @return role
     **/
    @ApiModelProperty(example = "BRAND", required = true, value = "The role of the party involved for this product.")
    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Party party = (Party) o;
        return Objects.equals(this.name, party.name) &&
                Objects.equals(this.type, party.type) &&
                Objects.equals(this.role, party.role);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name, type, role);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Party {\n");

        sb.append("    name: ").append(toIndentedString(name)).append("\n");
        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    role: ").append(toIndentedString(role)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

