/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * PerformanceIndicatorPeriod
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class PerformanceIndicatorPeriod {
    @SerializedName("week")
    private String week = null;

    @SerializedName("year")
    private String year = null;

    public PerformanceIndicatorPeriod week(String week) {
        this.week = week;
        return this;
    }

    /**
     * Week number in the ISO-8601 standard.
     *
     * @return week
     **/
    @ApiModelProperty(example = "05", required = true, value = "Week number in the ISO-8601 standard.")
    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public PerformanceIndicatorPeriod year(String year) {
        this.year = year;
        return this;
    }

    /**
     * Year number in the ISO-8601 standard.
     *
     * @return year
     **/
    @ApiModelProperty(example = "2019", required = true, value = "Year number in the ISO-8601 standard.")
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PerformanceIndicatorPeriod performanceIndicatorPeriod = (PerformanceIndicatorPeriod) o;
        return Objects.equals(this.week, performanceIndicatorPeriod.week) &&
                Objects.equals(this.year, performanceIndicatorPeriod.year);
    }

    @Override
    public int hashCode() {
        return Objects.hash(week, year);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PerformanceIndicatorPeriod {\n");

        sb.append("    week: ").append(toIndentedString(week)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

