/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Pricing
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Pricing {
    @SerializedName("bundlePrices")
    private List<BundlePrice> bundlePrices = new ArrayList<BundlePrice>();

    public Pricing bundlePrices(List<BundlePrice> bundlePrices) {
        this.bundlePrices = bundlePrices;
        return this;
    }

    public Pricing addBundlePricesItem(BundlePrice bundlePricesItem) {
        this.bundlePrices.add(bundlePricesItem);
        return this;
    }

    /**
     * A set of prices (containing a quantity and selling price) that apply to this offer.
     *
     * @return bundlePrices
     **/
    @ApiModelProperty(required = true, value = "A set of prices (containing a quantity and selling price) that apply to this offer.")
    public List<BundlePrice> getBundlePrices() {
        return bundlePrices;
    }

    public void setBundlePrices(List<BundlePrice> bundlePrices) {
        this.bundlePrices = bundlePrices;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Pricing pricing = (Pricing) o;
        return Objects.equals(this.bundlePrices, pricing.bundlePrices);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bundlePrices);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Pricing {\n");

        sb.append("    bundlePrices: ").append(toIndentedString(bundlePrices)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

