/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A single product.
 */
@ApiModel(description = "A single product.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class Product {
    @SerializedName("ean")
    private String ean = null;

    @SerializedName("relevanceScores")
    private List<RelevanceScore> relevanceScores = null;

    @SerializedName("maximumPrice")
    private BigDecimal maximumPrice = null;

    public Product ean(String ean) {
        this.ean = ean;
        return this;
    }

    /**
     * The EAN number associated with this product.
     *
     * @return ean
     **/
    @ApiModelProperty(example = "0000007740404", required = true, value = "The EAN number associated with this product.")
    public String getEan() {
        return ean;
    }

    public void setEan(String ean) {
        this.ean = ean;
    }

    public Product relevanceScores(List<RelevanceScore> relevanceScores) {
        this.relevanceScores = relevanceScores;
        return this;
    }

    public Product addRelevanceScoresItem(RelevanceScore relevanceScoresItem) {
        if (this.relevanceScores == null) {
            this.relevanceScores = new ArrayList<RelevanceScore>();
        }
        this.relevanceScores.add(relevanceScoresItem);
        return this;
    }

    /**
     * Get relevanceScores
     *
     * @return relevanceScores
     **/
    @ApiModelProperty(value = "")
    public List<RelevanceScore> getRelevanceScores() {
        return relevanceScores;
    }

    public void setRelevanceScores(List<RelevanceScore> relevanceScores) {
        this.relevanceScores = relevanceScores;
    }

    public Product maximumPrice(BigDecimal maximumPrice) {
        this.maximumPrice = maximumPrice;
        return this;
    }

    /**
     * The maximum price a product can have in order to be part of the promotion.
     *
     * @return maximumPrice
     **/
    @ApiModelProperty(example = "21.5", value = "The maximum price a product can have in order to be part of the promotion.")
    public BigDecimal getMaximumPrice() {
        return maximumPrice;
    }

    public void setMaximumPrice(BigDecimal maximumPrice) {
        this.maximumPrice = maximumPrice;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Product product = (Product) o;
        return Objects.equals(this.ean, product.ean) &&
                Objects.equals(this.relevanceScores, product.relevanceScores) &&
                Objects.equals(this.maximumPrice, product.maximumPrice);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ean, relevanceScores, maximumPrice);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class Product {\n");

        sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
        sb.append("    relevanceScores: ").append(toIndentedString(relevanceScores)).append("\n");
        sb.append("    maximumPrice: ").append(toIndentedString(maximumPrice)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

