/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ReplenishmentResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ReplenishmentResponse {
    @SerializedName("replenishmentId")
    private String replenishmentId = null;

    @SerializedName("creationDateTime")
    private OffsetDateTime creationDateTime = null;

    @SerializedName("reference")
    private String reference = null;

    @SerializedName("labelingByBol")
    private Boolean labelingByBol = null;

    /**
     * Indicates the state of this replenishment order.
     */
    @JsonAdapter(StateEnum.Adapter.class)
    public enum StateEnum {
        ANNOUNCED("ANNOUNCED"),

        IN_TRANSIT("IN_TRANSIT"),

        ARRIVED_AT_WH("ARRIVED_AT_WH"),

        IN_PROGRESS_AT_WH("IN_PROGRESS_AT_WH"),

        CANCELLED("CANCELLED"),

        DONE("DONE");

        private String value;

        StateEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StateEnum fromValue(String text) {
            for (StateEnum b : StateEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<StateEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StateEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StateEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return StateEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("state")
    private StateEnum state = null;

    @SerializedName("deliveryInformation")
    private DeliveryInformation deliveryInformation = null;

    @SerializedName("pickupAppointment")
    private PickupAppointment pickupAppointment = null;

    @SerializedName("numberOfLoadCarriers")
    private Integer numberOfLoadCarriers = null;

    @SerializedName("loadCarriers")
    private List<LoadCarrier> loadCarriers = new ArrayList<LoadCarrier>();

    @SerializedName("lines")
    private List<ReplenishmentLine> lines = new ArrayList<ReplenishmentLine>();

    @SerializedName("invalidLines")
    private List<InvalidReplenishmentLine> invalidLines = new ArrayList<InvalidReplenishmentLine>();

    @SerializedName("stateTransitions")
    private List<StateTransition> stateTransitions = new ArrayList<StateTransition>();

    public ReplenishmentResponse replenishmentId(String replenishmentId) {
        this.replenishmentId = replenishmentId;
        return this;
    }

    /**
     * The unique identifier of the replenishment.
     *
     * @return replenishmentId
     **/
    @ApiModelProperty(example = "2312078154", required = true, value = "The unique identifier of the replenishment.")
    public String getReplenishmentId() {
        return replenishmentId;
    }

    public void setReplenishmentId(String replenishmentId) {
        this.replenishmentId = replenishmentId;
    }

    public ReplenishmentResponse creationDateTime(OffsetDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
        return this;
    }

    /**
     * The date and time when this replenishment was created. In ISO 8601 format.
     *
     * @return creationDateTime
     **/
    @ApiModelProperty(example = "2021-01-01T08:00:00+01:00", required = true, value = "The date and time when this replenishment was created. In ISO 8601 format.")
    public OffsetDateTime getCreationDateTime() {
        return creationDateTime;
    }

    public void setCreationDateTime(OffsetDateTime creationDateTime) {
        this.creationDateTime = creationDateTime;
    }

    public ReplenishmentResponse reference(String reference) {
        this.reference = reference;
        return this;
    }

    /**
     * Custom user defined reference to identify the replenishment.
     *
     * @return reference
     **/
    @ApiModelProperty(example = "REFERENCE1", required = true, value = "Custom user defined reference to identify the replenishment.")
    public String getReference() {
        return reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public ReplenishmentResponse labelingByBol(Boolean labelingByBol) {
        this.labelingByBol = labelingByBol;
        return this;
    }

    /**
     * Indicates whether the replenishment will be labeled by bol.com or not.
     *
     * @return labelingByBol
     **/
    @ApiModelProperty(example = "false", required = true, value = "Indicates whether the replenishment will be labeled by bol.com or not.")
    public Boolean isLabelingByBol() {
        return labelingByBol;
    }

    public void setLabelingByBol(Boolean labelingByBol) {
        this.labelingByBol = labelingByBol;
    }

    public ReplenishmentResponse state(StateEnum state) {
        this.state = state;
        return this;
    }

    /**
     * Indicates the state of this replenishment order.
     *
     * @return state
     **/
    @ApiModelProperty(example = "ANNOUNCED", required = true, value = "Indicates the state of this replenishment order.")
    public StateEnum getState() {
        return state;
    }

    public void setState(StateEnum state) {
        this.state = state;
    }

    public ReplenishmentResponse deliveryInformation(DeliveryInformation deliveryInformation) {
        this.deliveryInformation = deliveryInformation;
        return this;
    }

    /**
     * Get deliveryInformation
     *
     * @return deliveryInformation
     **/
    @ApiModelProperty(required = true, value = "")
    public DeliveryInformation getDeliveryInformation() {
        return deliveryInformation;
    }

    public void setDeliveryInformation(DeliveryInformation deliveryInformation) {
        this.deliveryInformation = deliveryInformation;
    }

    public ReplenishmentResponse pickupAppointment(PickupAppointment pickupAppointment) {
        this.pickupAppointment = pickupAppointment;
        return this;
    }

    /**
     * Get pickupAppointment
     *
     * @return pickupAppointment
     **/
    @ApiModelProperty(value = "")
    public PickupAppointment getPickupAppointment() {
        return pickupAppointment;
    }

    public void setPickupAppointment(PickupAppointment pickupAppointment) {
        this.pickupAppointment = pickupAppointment;
    }

    public ReplenishmentResponse numberOfLoadCarriers(Integer numberOfLoadCarriers) {
        this.numberOfLoadCarriers = numberOfLoadCarriers;
        return this;
    }

    /**
     * The number of load carriers in this shipment.
     *
     * @return numberOfLoadCarriers
     **/
    @ApiModelProperty(example = "1", value = "The number of load carriers in this shipment.")
    public Integer getNumberOfLoadCarriers() {
        return numberOfLoadCarriers;
    }

    public void setNumberOfLoadCarriers(Integer numberOfLoadCarriers) {
        this.numberOfLoadCarriers = numberOfLoadCarriers;
    }

    public ReplenishmentResponse loadCarriers(List<LoadCarrier> loadCarriers) {
        this.loadCarriers = loadCarriers;
        return this;
    }

    public ReplenishmentResponse addLoadCarriersItem(LoadCarrier loadCarriersItem) {
        this.loadCarriers.add(loadCarriersItem);
        return this;
    }

    /**
     * Get loadCarriers
     *
     * @return loadCarriers
     **/
    @ApiModelProperty(required = true, value = "")
    public List<LoadCarrier> getLoadCarriers() {
        return loadCarriers;
    }

    public void setLoadCarriers(List<LoadCarrier> loadCarriers) {
        this.loadCarriers = loadCarriers;
    }

    public ReplenishmentResponse lines(List<ReplenishmentLine> lines) {
        this.lines = lines;
        return this;
    }

    public ReplenishmentResponse addLinesItem(ReplenishmentLine linesItem) {
        this.lines.add(linesItem);
        return this;
    }

    /**
     * Get lines
     *
     * @return lines
     **/
    @ApiModelProperty(required = true, value = "")
    public List<ReplenishmentLine> getLines() {
        return lines;
    }

    public void setLines(List<ReplenishmentLine> lines) {
        this.lines = lines;
    }

    public ReplenishmentResponse invalidLines(List<InvalidReplenishmentLine> invalidLines) {
        this.invalidLines = invalidLines;
        return this;
    }

    public ReplenishmentResponse addInvalidLinesItem(InvalidReplenishmentLine invalidLinesItem) {
        this.invalidLines.add(invalidLinesItem);
        return this;
    }

    /**
     * Get invalidLines
     *
     * @return invalidLines
     **/
    @ApiModelProperty(required = true, value = "")
    public List<InvalidReplenishmentLine> getInvalidLines() {
        return invalidLines;
    }

    public void setInvalidLines(List<InvalidReplenishmentLine> invalidLines) {
        this.invalidLines = invalidLines;
    }

    public ReplenishmentResponse stateTransitions(List<StateTransition> stateTransitions) {
        this.stateTransitions = stateTransitions;
        return this;
    }

    public ReplenishmentResponse addStateTransitionsItem(StateTransition stateTransitionsItem) {
        this.stateTransitions.add(stateTransitionsItem);
        return this;
    }

    /**
     * Get stateTransitions
     *
     * @return stateTransitions
     **/
    @ApiModelProperty(required = true, value = "")
    public List<StateTransition> getStateTransitions() {
        return stateTransitions;
    }

    public void setStateTransitions(List<StateTransition> stateTransitions) {
        this.stateTransitions = stateTransitions;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReplenishmentResponse replenishmentResponse = (ReplenishmentResponse) o;
        return Objects.equals(this.replenishmentId, replenishmentResponse.replenishmentId) &&
                Objects.equals(this.creationDateTime, replenishmentResponse.creationDateTime) &&
                Objects.equals(this.reference, replenishmentResponse.reference) &&
                Objects.equals(this.labelingByBol, replenishmentResponse.labelingByBol) &&
                Objects.equals(this.state, replenishmentResponse.state) &&
                Objects.equals(this.deliveryInformation, replenishmentResponse.deliveryInformation) &&
                Objects.equals(this.pickupAppointment, replenishmentResponse.pickupAppointment) &&
                Objects.equals(this.numberOfLoadCarriers, replenishmentResponse.numberOfLoadCarriers) &&
                Objects.equals(this.loadCarriers, replenishmentResponse.loadCarriers) &&
                Objects.equals(this.lines, replenishmentResponse.lines) &&
                Objects.equals(this.invalidLines, replenishmentResponse.invalidLines) &&
                Objects.equals(this.stateTransitions, replenishmentResponse.stateTransitions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(replenishmentId, creationDateTime, reference, labelingByBol, state, deliveryInformation, pickupAppointment, numberOfLoadCarriers, loadCarriers, lines, invalidLines, stateTransitions);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ReplenishmentResponse {\n");

        sb.append("    replenishmentId: ").append(toIndentedString(replenishmentId)).append("\n");
        sb.append("    creationDateTime: ").append(toIndentedString(creationDateTime)).append("\n");
        sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
        sb.append("    labelingByBol: ").append(toIndentedString(labelingByBol)).append("\n");
        sb.append("    state: ").append(toIndentedString(state)).append("\n");
        sb.append("    deliveryInformation: ").append(toIndentedString(deliveryInformation)).append("\n");
        sb.append("    pickupAppointment: ").append(toIndentedString(pickupAppointment)).append("\n");
        sb.append("    numberOfLoadCarriers: ").append(toIndentedString(numberOfLoadCarriers)).append("\n");
        sb.append("    loadCarriers: ").append(toIndentedString(loadCarriers)).append("\n");
        sb.append("    lines: ").append(toIndentedString(lines)).append("\n");
        sb.append("    invalidLines: ").append(toIndentedString(invalidLines)).append("\n");
        sb.append("    stateTransitions: ").append(toIndentedString(stateTransitions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

