/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * SearchTermsPeriod
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class SearchTermsPeriod {
    @SerializedName("day")
    private String day = null;

    @SerializedName("week")
    private String week = null;

    @SerializedName("month")
    private String month = null;

    @SerializedName("year")
    private String year = null;

    public SearchTermsPeriod day(String day) {
        this.day = day;
        return this;
    }

    /**
     * Day number in the ISO-8601 standard.
     *
     * @return day
     **/
    @ApiModelProperty(example = "19", value = "Day number in the ISO-8601 standard.")
    public String getDay() {
        return day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public SearchTermsPeriod week(String week) {
        this.week = week;
        return this;
    }

    /**
     * Week number in the ISO-8601 standard.
     *
     * @return week
     **/
    @ApiModelProperty(example = "41", value = "Week number in the ISO-8601 standard.")
    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public SearchTermsPeriod month(String month) {
        this.month = month;
        return this;
    }

    /**
     * Month number in the ISO-8601 standard.
     *
     * @return month
     **/
    @ApiModelProperty(example = "11", value = "Month number in the ISO-8601 standard.")
    public String getMonth() {
        return month;
    }

    public void setMonth(String month) {
        this.month = month;
    }

    public SearchTermsPeriod year(String year) {
        this.year = year;
        return this;
    }

    /**
     * Year number in the ISO-8601 standard.
     *
     * @return year
     **/
    @ApiModelProperty(example = "2020", value = "Year number in the ISO-8601 standard.")
    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SearchTermsPeriod searchTermsPeriod = (SearchTermsPeriod) o;
        return Objects.equals(this.day, searchTermsPeriod.day) &&
                Objects.equals(this.week, searchTermsPeriod.week) &&
                Objects.equals(this.month, searchTermsPeriod.month) &&
                Objects.equals(this.year, searchTermsPeriod.year);
    }

    @Override
    public int hashCode() {
        return Objects.hash(day, week, month, year);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SearchTermsPeriod {\n");

        sb.append("    day: ").append(toIndentedString(day)).append("\n");
        sb.append("    week: ").append(toIndentedString(week)).append("\n");
        sb.append("    month: ").append(toIndentedString(month)).append("\n");
        sb.append("    year: ").append(toIndentedString(year)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

