/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ShipmentsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class ShipmentsResponse {
    @SerializedName("shipments")
    private List<ReducedShipment> shipments = new ArrayList<ReducedShipment>();

    public ShipmentsResponse shipments(List<ReducedShipment> shipments) {
        this.shipments = shipments;
        return this;
    }

    public ShipmentsResponse addShipmentsItem(ReducedShipment shipmentsItem) {
        this.shipments.add(shipmentsItem);
        return this;
    }

    /**
     * Get shipments
     *
     * @return shipments
     **/
    @ApiModelProperty(required = true, value = "")
    public List<ReducedShipment> getShipments() {
        return shipments;
    }

    public void setShipments(List<ReducedShipment> shipments) {
        this.shipments = shipments;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ShipmentsResponse shipmentsResponse = (ShipmentsResponse) o;
        return Objects.equals(this.shipments, shipmentsResponse.shipments);
    }

    @Override
    public int hashCode() {
        return Objects.hash(shipments);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ShipmentsResponse {\n");

        sb.append("    shipments: ").append(toIndentedString(shipments)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

