/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UploadReportAsset
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-12-04T20:35:33.904+01:00")
public class UploadReportAsset {
    @SerializedName("url")
    private String url = null;

    @SerializedName("labels")
    private List<String> labels = new ArrayList<String>();

    /**
     * The processing state of the submitted asset.
     */
    @JsonAdapter(StatusEnum.Adapter.class)
    public enum StatusEnum {
        IN_PROGRESS("IN_PROGRESS"),

        DECLINED("DECLINED"),

        PUBLISHED("PUBLISHED");

        private String value;

        StatusEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static StatusEnum fromValue(String text) {
            for (StatusEnum b : StatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<StatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public StatusEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return StatusEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("status")
    private StatusEnum status = null;

    /**
     * The reason code explaining why the value was rejected.
     */
    @JsonAdapter(SubStatusEnum.Adapter.class)
    public enum SubStatusEnum {
        DELETED("DELETED"),

        DOWNLOAD_FAILED_404("DOWNLOAD_FAILED_404"),

        DOWNLOAD_FAILED_UNAUTHORIZED("DOWNLOAD_FAILED_UNAUTHORIZED"),

        IMAGE_FLAGGED_AS_DUPLICATE("IMAGE_FLAGGED_AS_DUPLICATE"),

        IMAGE_RATE_LIMITED("IMAGE_RATE_LIMITED"),

        IMPORT_FAILED("IMPORT_FAILED"),

        LABEL_UPDATED("LABEL_UPDATED"),

        MATCH_TO_PRODUCT_FAILED("MATCH_TO_PRODUCT_FAILED"),

        NOT_VALID_FOR_IMPORT("NOT_VALID_FOR_IMPORT"),

        PUBLISHED("PUBLISHED"),

        RECEIVED("RECEIVED"),

        SCORED_OTHER_IMAGE_WON("SCORED_OTHER_IMAGE_WON"),

        STORED("STORED"),

        SUPPLIED_FLAGGED_AS_BLACKLISTED("SUPPLIED_FLAGGED_AS_BLACKLISTED"),

        UNKNOWN("UNKNOWN"),

        UNPUBLISHED("UNPUBLISHED"),

        UNSUPPORTED_MIMETYPE("UNSUPPORTED_MIMETYPE"),

        UPLOAD_CANCELLED("UPLOAD_CANCELLED"),

        UPLOAD_DEADLINE_REACHED("UPLOAD_DEADLINE_REACHED"),

        UPLOAD_FAILED("UPLOAD_FAILED"),

        UPLOAD_REJECTED("UPLOAD_REJECTED");

        private String value;

        SubStatusEnum(String value) {
            this.value = value;
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }

        public static SubStatusEnum fromValue(String text) {
            for (SubStatusEnum b : SubStatusEnum.values()) {
                if (String.valueOf(b.value).equals(text)) {
                    return b;
                }
            }
            return null;
        }

        public static class Adapter extends TypeAdapter<SubStatusEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final SubStatusEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public SubStatusEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return SubStatusEnum.fromValue(String.valueOf(value));
            }
        }
    }

    @SerializedName("subStatus")
    private SubStatusEnum subStatus = null;

    @SerializedName("subStatusDescription")
    private String subStatusDescription = null;

    public UploadReportAsset url(String url) {
        this.url = url;
        return this;
    }

    /**
     * The URL of the asset.
     *
     * @return url
     **/
    @ApiModelProperty(example = "http://example.com", required = true, value = "The URL of the asset.")
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public UploadReportAsset labels(List<String> labels) {
        this.labels = labels;
        return this;
    }

    public UploadReportAsset addLabelsItem(String labelsItem) {
        this.labels.add(labelsItem);
        return this;
    }

    /**
     * The label(s) of the asset.
     *
     * @return labels
     **/
    @ApiModelProperty(example = "\"[ \\\"FRONT\\\" ]\"", required = true, value = "The label(s) of the asset.")
    public List<String> getLabels() {
        return labels;
    }

    public void setLabels(List<String> labels) {
        this.labels = labels;
    }

    public UploadReportAsset status(StatusEnum status) {
        this.status = status;
        return this;
    }

    /**
     * The processing state of the submitted asset.
     *
     * @return status
     **/
    @ApiModelProperty(example = "DECLINED", required = true, value = "The processing state of the submitted asset.")
    public StatusEnum getStatus() {
        return status;
    }

    public void setStatus(StatusEnum status) {
        this.status = status;
    }

    public UploadReportAsset subStatus(SubStatusEnum subStatus) {
        this.subStatus = subStatus;
        return this;
    }

    /**
     * The reason code explaining why the value was rejected.
     *
     * @return subStatus
     **/
    @ApiModelProperty(example = "DOWNLOAD_FAILED_404", value = "The reason code explaining why the value was rejected.")
    public SubStatusEnum getSubStatus() {
        return subStatus;
    }

    public void setSubStatus(SubStatusEnum subStatus) {
        this.subStatus = subStatus;
    }

    public UploadReportAsset subStatusDescription(String subStatusDescription) {
        this.subStatusDescription = subStatusDescription;
        return this;
    }

    /**
     * The reason explaining why the value was rejected.
     *
     * @return subStatusDescription
     **/
    @ApiModelProperty(example = "Failed to download.", value = "The reason explaining why the value was rejected.")
    public String getSubStatusDescription() {
        return subStatusDescription;
    }

    public void setSubStatusDescription(String subStatusDescription) {
        this.subStatusDescription = subStatusDescription;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UploadReportAsset uploadReportAsset = (UploadReportAsset) o;
        return Objects.equals(this.url, uploadReportAsset.url) &&
                Objects.equals(this.labels, uploadReportAsset.labels) &&
                Objects.equals(this.status, uploadReportAsset.status) &&
                Objects.equals(this.subStatus, uploadReportAsset.subStatus) &&
                Objects.equals(this.subStatusDescription, uploadReportAsset.subStatusDescription);
    }

    @Override
    public int hashCode() {
        return Objects.hash(url, labels, status, subStatus, subStatusDescription);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class UploadReportAsset {\n");

        sb.append("    url: ").append(toIndentedString(url)).append("\n");
        sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
        sb.append("    status: ").append(toIndentedString(status)).append("\n");
        sb.append("    subStatus: ").append(toIndentedString(subStatus)).append("\n");
        sb.append("    subStatusDescription: ").append(toIndentedString(subStatusDescription)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

