/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.InventoryResponse;
import org.junit.Ignore;
import org.junit.Test;

import java.util.List;

/**
 * API tests for InventoryApi
 */
@Ignore
public class InventoryApiTest {

    private final InventoryApi api = new InventoryApi();


    /**
     * Get LVB/FBB inventory
     * <p>
     * The inventory endpoint is a specific LVB/FBB endpoint. It provides a paginated list containing your fulfilment by bol.com inventory. This endpoint does not provide information about your own stock.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void getInventoryTest() throws Exception {
        Integer page = null;
        List<String> quantity = null;
        String stock = null;
        String state = null;
        String query = null;
        InventoryResponse response = api.getInventory(page, quantity, stock, state, query);

        // TODO: test validations
    }

}
