/*
 * v8 - Retailer API
 * The bol.com API for retailers.
 *
 * OpenAPI spec version: 8.x
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ChangeTransportRequest;
import io.swagger.client.model.ProcessStatus;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for TransportsApi
 */
@Ignore
public class TransportsApiTest {

    private final TransportsApi api = new TransportsApi();


    /**
     * Add transport information by transport id
     * <p>
     * Add information to an existing transport. The transport id is part of the shipment. You can retrieve the transport id through the GET shipment list request.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void addTransportInformationByTransportIdTest() throws Exception {
        String transportId = null;
        ChangeTransportRequest body = null;
        ProcessStatus response = api.addTransportInformationByTransportId(transportId, body);

        // TODO: test validations
    }

}
